version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-password}
      TZ: ${TZ:-Asia/Tokyo}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-store:/var/lib/mysql
  app:
    build:
      context: .
      args:
        env: development
    environment:
      DATABASE_DEV_HOST: db
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-password}
      SAMPLE_USER_PASSWORD: ${SAMPLE_USER_PASSWORD:-Password}
      TZ: ${TZ:-Asia/Tokyo}
      PORT: ${PORT:-3000}
      HOST_DEFAULT_URL_HOST: ${HOST_DEFAULT_URL_HOST:-localhost}
      HOST_DEFAULT_URL_PORT: ${HOST_DEFAULT_URL_PORT:-3000}
      SENDER_EMAIL_ADDRESS: ${SENDER_EMAIL_ADDRESS:-testNoteNext@example.com}
      MAILER_DEFAULT_URL_HOST: ${MAILER_DEFAULT_URL_HOST:-localhost}
      MAILER_DEFAULT_URL_PORT: ${MAILER_DEFAULT_URL_PORT:-3000}
      MAILER_SMTP_ADDRESS: ${MAILER_SMTP_ADDRESS:-smtp}
      MAILER_SMTP_PORT: ${MAILER_SMTP_PORT:-1025}
      FRONT_SERVER_ORIGIN: ${FRONT_SERVER_ORIGIN:-http://localhost:8888}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    volumes:
      - .:/app
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  db-store:
